### ISSUE TITLE
Simple Spelling Mistakes.

### ISSUE THREAD

**Issue by migarabhanu** [Binura-Weragoda/Quiz#2]
I've found some simple spelling mistakes with the[ Quiz program](https://github.com/Binura-Weragoda/Quiz/blob/main/py.py) developed by @Binura-Weragoda.

**Comment by migarabhanu** [comment]
Then, I solved those [mistakes](https://github.com/Binura-Weragoda/Quiz/compare/main...migarabhanu:main) and made a [pull request](https://github.com/Binura-Weragoda/Quiz/pull/1). So, @Binura-Weragoda you can easily solve those mistakes by merge my pull request.

**Comment by Binura-Weragoda** [comment]
Hi ! Everyone , There are no any spelling mistakes in my py.py project . So you can download my py.py by my site and face to the quiz game ! 

Thank-You !

@All rights reserved for @Binura-Weragoda

**Comment by Binura-Weragoda** [comment]
By this link you can download that - https://binura-weragoda.github.io/Quiz/py.py 

Just Click then It will be download !

**Comment by migarabhanu** [comment]
**You can check those mistakes by click on** [HERE](https://github.com/Binura-Weragoda/Quiz/compare/main...migarabhanu:main). 
**Just solve them by merging this** [pull request](https://github.com/Binura-Weragoda/Quiz/pull/1).
